import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Providers } from './providers';
import { ReactNode } from 'react';
import { TransactionModal } from '@/components/transactions/transaction-modal';
import { getTransactionFormData } from '@/db/queries/transactions';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Personal Finances App',
  description: 'Generated by Personal Finances App',
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const { currencies, currentCurrency, categories } =
    await getTransactionFormData();

  return (
    <html lang="en" className="h-full">
      <body className={cn(inter.className, 'h-full')}>
        <Providers
          currencies={currencies}
          currentCurrency={currentCurrency}
          categories={categories}
        >
          <div className="fixed bottom-10 z-50 right-5 md:hidden">
            <TransactionModal />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
